name: "Setup and Build"
description: "Run steps to build project"
runs:
  using: "composite"
  steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Configure Step
      uses: ./.github/actions/configure

    - name: Cache local
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Run AssembleRelease
      run: ./gradlew module:assembleRelease
      shell: bash