name: Android Deploy
run-name: Deploy Artifact execute by @${{ github.actor }}

on: [ workflow_dispatch ]

env:
  REPO_USERID: ${{ secrets.REPO_USERID }}
  REPO_TOKEN: ${{ secrets.REPO_TOKEN }}

jobs:
  deploy:
    name: Artifact
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Project
        uses: ./.github/actions/android

      - name: Run AssembleRelease
        run: ./gradlew module:assembleRelease
        shell: bash

      - name: Run Upload Artifact
        run: ./gradlew module:publishModulePublicationToArtifactRepository