name: Android Artifact
run-name: Deploy to ${{ inputs.deploy_target }} by @${{ github.actor }}

on: [ workflow_dispatch ]

env:
  REPO_USERID: ${{ secrets.REPO_USERID }}
  REPO_TOKEN: ${{ secrets.REPO_TOKEN }}

jobs:
  artifact:
    name: Artifact
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure Step
        uses: ./.github/actions/configure

      - name: Cache local
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Run Jacoco Test Coverage Verification
        run: ./gradlew module:jacocoTestCoverageVerification


  code-analysis:
    name: Code Analysis
    needs: [ artifact ]
    runs-on: self-hosted
    steps:
      - name: Run Lint
        run: ./gradlew module:lintDebug